EXP_NAME = "test"
ENV = 'MountainCar-v0'
TARGET_NAMES = [
"full",
]
SOURCE_NAMES = [
"standard",
]
VERBOSE = False
EXPLORATION_PROBA_START = 0.2
EXPLORATION_PROBA_END = 0.2
MAX_ITER = 1000
NUM_TRIALS_SOURCES = 300
NUM_TRIALS_TARGETS = [100]
NUM_TRIALS_EVAL = 100
RELOAD_WEIGHTS = False
DISCOUNT = .9
ELIGIBILITY = False
TRAIN = True
DEEP_MODES = [1]