EXP_NAME = "test"
ENV = 'MountainCar-v0'
TARGET_NAMES = [
"full",
]
SOURCE_NAMES = [
"standard",
]
VERBOSE = False
EXPLORATION_PROBA_START = 1.
EXPLORATION_PROBA_END = 0.1
MAX_ITER = 1000
NUM_TRIALS_SOURCES = 100
NUM_TRIALS_TARGETS = [100]
NUM_TRIALS_EVAL = 100
RELOAD_WEIGHTS = False
DISCOUNT = 1
ELIGIBILITY = False
TRAIN = True
DEEP_MODES = [1]